clients/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from clients.views import *

urlpatterns = [
    path('', clients_home, name='clients_home'),
    path('hotel', clients_hotel, name='clients_hotel'),
    path('restaurant', clients_restaurant, name='clients_restaurant'),
    path('profile', clients_profile, name='clients_profile'),
    path('reservations', clients_reservations, name='clients_reservations'),
]

hotel_management/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from hotel_management.views import home, set_language
from members.urls import *
from restaurant.views import *
from cleaning import urls

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('accounts/', include('members.urls'), name='members'),
    path('administration/', include('administration.urls'), name='administration'),
    path('restaurant/', include('restaurant.urls'), name='restaurant'),
    path('cleaning/', include('cleaning.urls'), name='cleaning'),
    path('superuser/', include('super_user.urls'), name='superuser'),
    path('clients/', include('clients.urls'), name='clients'),
    path('accounting/', include('accounting.urls'), name='accounting'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

extra_urlpatterns = [
    path('i18n/setlang/', set_language, name='set_language'),
]

urlpatterns += extra_urlpatterns

clients/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from datetime import date, timedelta
from clients.models import *

class AvailabilityHotelClientsCheckForm(forms.Form):
    room_type = forms.ChoiceField(
        choices=[('Ind', 'Individual'), ('Dob', 'Doble'), ('Del', 'Deluxe'), ('Sui', 'Suite')],
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_room_type'})
    )
    check_in_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control datepicker', 'id': 'id_check_in_date'})
    )
    check_out_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control datepicker', 'id': 'id_check_out_date'})
    )
    number_of_guests = forms.ChoiceField(
        choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_room_type'})
    )

class AvailabilityRestaurantClientCheckForm(forms.Form):
    number_of_people = forms.IntegerField(label="Número de Personas")
    date = forms.DateField(
        label="Fecha",
        widget=forms.DateInput(attrs={'class': 'form-control datepicker', 'id': 'id_date'})
    )
    time = forms.ChoiceField(
        label="Turno",
        choices=[
            ('breakfast_1', 'Desayuno - Primer Turno'),
            ('breakfast_2', 'Desayuno - Segundo Turno'),
            ('lunch_1', 'Comida - Primer Turno'),
            ('lunch_2', 'Comida - Segundo Turno'),
            ('dinner_1', 'Cena - Primer Turno'),
            ('dinner_2', 'Cena - Segundo Turno'),
        ],
        widget=forms.Select(attrs={'class': 'form-control', 'id': 'id_time'})
    )

class ProfileClientForm(forms.ModelForm):
    class Meta:
        model = ProfileClient
        fields = ['dni', 'first_name', 'last_name', 'date_of_birth', 'email', 'phone']

        widgets = {
            'dni': forms.TextInput(
                attrs={
                    'placeholder': 'DNI/NIE',
                    'class': 'form-control'
                }
            ),
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombre',
                    'class': 'form-control'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Apellido',
                    'class': 'form-control'
                }
            ),
            'date_of_birth': forms.DateInput(
                attrs={
                    'placeholder': 'aaaa-mm-dd',
                    'class': 'form-control datepicker'
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Correo electrónico',
                    'class': 'form-control'
                }
            ),
            'phone': forms.NumberInput(
                attrs={
                    'placeholder': 'Número de teléfono',
                    'class': 'form-control'
                }
            ),
        }
        labels = {
            'dni': 'Documento de Identidad',
            'first_name': 'Nombre',
            'last_name': 'Apellido',
            'date_of_birth': 'Fecha de Nacimiento',
            'email': 'Correo Electrónico',
            'phone': 'Teléfono',
            'check_in_date': 'Fecha de Entrada',
            'check_out_date': 'Fecha de Salida',
            'number_of_guests': 'Número de Huéspedes',
        }

templates/reception/add_check_in_form.html
{% extends './reservations.html' %}

{% load i18n %}
{% load static %}


{% block title %}{% trans "Create Check-In" %}{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mt-5">{% block card_header %}{% trans "Reservation Check-In" %}{% endblock %}: {{ reservation }}</h1>
        <hr>
        <div class="card mt-4">
            <div class="card-body shadow">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary me-2 mt-3">
                        <i class="fas fa-check"></i> {% trans "Submit" %}
                    </button>
                    <a class="btn btn-secondary mt-3" href="{% url 'reservation_detail' reservation_type=reservation_type reservation_id=reservation_id %}">
                        <i class="fas fa-arrow-left"></i> {% trans "Back to Reservations" %}
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/reception/add_check_out_form.html
{% extends './add_check_in_form.html' %}

{% load i18n %}
{% load static %}


{% block title %}{% trans "Create Check-Out" %}{% endblock %}

{% block card_header %}{% trans "Reservation Check-Out" %}{% endblock %}

templates/reception/add_reservation_form.html
{% extends 'reception/administration_base.html' %}
{% load i18n %}
{% load static %}

{% block title %}Add Reservation{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-5">Add Reservation</h1>
    {% if reservation_type == 'hotel' %}
        <h2 class="mt-3">Available Rooms</h2>
        <form id="reservation-form" method="post" class="mt-4">
            {% csrf_token %}
            {% if available_rooms %}
                <label for="room-select">Select a room:</label>
                <select class="form-select" id="room-select" name="room">
                    {% for room in available_rooms %}
                        <option class="list-group-item" value="{{ room.number }}">{{ room }}</option>
                    {% endfor %}
                </select>
                <p>Price: <span id="room.type">value="{{ room.price }}"</span></p>
                <h2 class="mt-3 mb-3">Reservation data</h2>
                {{ reservation_form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Complete Reservation</button>
            {% else %}
                <p>No rooms available for the selected dates and type.</p>
                <a href="{% url 'add_reservation' reservation_type=reservation_type %}" class="mt-4 btn btn-primary">Check other options</a>
            {% endif %}
        </form>
    {% else %}
        <h2 class="mt-3">Available Tables</h2>
        <form id="reservation-form" method="post" class="mt-4">
            {% csrf_token %}
            {% if available_tables %}
                <label for="table-select">Select a table:</label>
                <select class="form-select" id="table-select" name="table">
                    {% for table in available_tables %}
                        <option class="list-group-item" value="{{ table.id }}">{{ table }}</option>
                    {% endfor %}
                </select>
                <h2 class="mt-3 mb-3">Reservation data</h2>
                {{ reservation_form.as_p }}
                <button type="submit" class="btn btn-primary mt-3">Complete Reservation</button>
            {% else %}
                <p>No tables available for the selected date, time, and number of people.</p>
                <a href="{% url 'add_reservation' reservation_type=reservation_type %}" class="mt-4 btn btn-primary">Check other options</a>
            {% endif %}
        </form>
    {% endif %}
</div>

<head>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha584-gYcCR2aQzbUhT2tlr3BsXvR0JmW/sNclUyZ4aJzgtQAxkpik0yYCLPXv8ONnOnj0" crossorigin="anonymous">
</head>

<script>
  $('.datepicker').datepicker({
    format: 'yyyy-mm-dd',
    autoclose: true
  });

  $(document).ready(function() {
        $('#room-select').change(function() {
            var roomType = $(this).val();
            var roomPrice = calculateRoomPrice(roomType);
            $('#price-value').text(roomPrice + ' €');
        });

        function calculateRoomPrice(roomType) {
            var roomPrices = {
                'Ind': 45,
                'Dob': 75,
                'Sui': 125,
                'Del': 100,
                'Individual': 45,
                'Doble': 75,
                'Suite': 125,
                'Deluxe': 100,
            };
            return roomPrices[roomType];
        }
    });
</script>


{% endblock %}

templates/reception/administration_base.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}


{% block navbar-list %}
    <li class="nav-item">
        <a class="nav-link" aria-current="page" href="{% url 'reservations_list' reservation_type='hotel' %}">{% trans "Room reservations" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'reservations_list' reservation_type='restaurant' %}">{% trans "Restaurant reservations" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'cancelled_reservations_list' reservation_type='hotel' %}">{% trans "Cancelled room reservations" %}</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'cancelled_reservations_list' reservation_type='restaurant' %}">{% trans "Cancelled restaurant reservations" %}</a>
    </li>
{% endblock %}

templates/reception/availability_form.html
{% extends 'reception/administration_base.html' %}

{% block title %}Check Availability{% endblock %}

{% block content %}
<div class="container">
  <h1 class="mt-5">Check Availability</h1>

  <form id="availability-form" method="post" class="mt-4">
    {% csrf_token %}

    {% if reservation_type == 'hotel' %}
        <div class="form-group row mb-3">
          <label for="id_check_in_date" class="col-sm-2 col-form-label">Check-In Date</label>
          <div class="col-sm-10">
            {{ availability_form.check_in_date }}
          </div>
        </div>

        <div class="form-group row mb-3">
          <label for="id_check_out_date" class="col-sm-2 col-form-label">Check-Out Date</label>
          <div class="col-sm-10">
            {{ availability_form.check_out_date }}
          </div>
        </div>

        <div class="form-group row mb-3">
          <label for="id_room_type" class="col-sm-2 col-form-label">Room Type</label>
          <div class="col-sm-10">
            {{ availability_form.room_type }}
          </div>
        </div>
    {% else %}
        <div class="form-group row mb-3">
          <label for="id_date" class="col-sm-2 col-form-label">Date</label>
          <div class="col-sm-10">
            {{ availability_form.date }}
          </div>
        </div>

        <div class="form-group row mb-3">
          <label for="id_time" class="col-sm-2 col-form-label">Time</label>
          <div class="col-sm-10">
            {{ availability_form.time }}
          </div>
        </div>

        <div class="form-group row mb-3">
          <label for="id_number_of_people" class="col-sm-2 col-form-label">Number of People</label>
          <div class="col-sm-10">
            {{ availability_form.number_of_people }}
          </div>
        </div>
        {% endif %}

      <button type="submit" class="mt-4 btn btn-primary">Check Availability</button>
  </form>
</div>

<head>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" integrity="sha584-gYcCR2aQzbUhT2tlr3BsXvR0JmW/sNclUyZ4aJzgtQAxkpik0yYCLPXv8ONnOnj0" crossorigin="anonymous">
</head>

<script>
$(document).ready(function() {
  $('.datepicker').datepicker({
    format: 'yyyy-mm-dd', // Ajusta el formato según sea necesario (por ejemplo, 'dd/mm/yyyy')
    autoclose: true
  });
});
</script>

{% endblock %}

templates/reception/availability_result.html
{% extends 'reception/administration_base.html' %}
{% block title %}Available Rooms{% endblock %}
{% block content %}
<div class="container">
    <h1 class="mt-5">Available Rooms</h1>
    {% if available_rooms %}
    <ul>
        {% for room in available_rooms %}
        <li><a href="{% url 'reserve_room' room.id %}">{{ room.number }}</a> - {{ room.type }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No rooms available for the selected dates and type.</p>
    {% endif %}
</div>
{% endblock %}

templates/reception/cancelled_reservations.html
{% extends './administration_base.html' %}
{% load i18n %}
{% load static %}

{% block title %}{% trans "List of canceled reservations" %}{% endblock %}


{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-12">
                <h1>
                    {% if reservation_type == 'hotel' %}
                        {% trans "Cancelled room reservation list" %}
                    {% else %}
                        {% trans "Cancelled restaurant reservation list" %}
                    {% endif %}
                </h1>

                <form method="post" class="search-bar align-items-center">
                    {% csrf_token %}
                    <input type="search" name="query" placeholder="{% trans 'Search' %}" required>
                    <button type="submit">
                        <img src="{% static 'img/search-icon.png' %}" alt="search" width="40" height="30">
                    </button>
                </form>

                <h1 class="mt-5">{{ header }}</h1>
                <hr>
                <div class="accordion shadow" id="reservationAccordion">
                    {% for reservation in reservations %}
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="heading{{ reservation.id }}">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ reservation.id }}" aria-expanded="false" aria-controls="collapse{{ reservation.id }}">
                                    {{ reservation }}
                                </button>
                            </h2>
                            <div id="collapse{{ reservation.id }}" class="accordion-collapse collapse" aria-labelledby="heading{{ reservation.id }}" data-bs-parent="#checkInAccordion">
                                <div class="accordion-body">
                                    {% if reservation_type == 'hotel' %}
                                        <p><strong>{% trans "DNI" %}:</strong> {{ reservation.dni }}</p>
                                        <p><strong>{% trans "Room number" %}:</strong> {{ reservation.room_number }}</p>
                                    {% else %}
                                        <p><strong>{% trans "Name" %}:</strong> {{ reservation.name }}</p>
                                        <p><strong>{% trans "People" %}:</strong> {{ reservation.number_of_people }}</p>
                                    {% endif %}
                                    <div class="mt-3">
                                        <a href="{% url 'reservation_detail' reservation_type=reservation_type reservation_id=reservation.id %}" class="btn btn-primary me-2">
                                            <i class="fas fa-eye"></i> {% trans "Details" %}
                                        </a>
                                        <!--
                                        <a href="{% url 'edit_reservation' reservation_type=reservation_type reservation_id=reservation.id %}" class="btn btn-warning me-2">
                                            <i class="fas fa-edit"></i> {% trans "Edit" %}
                                        </a>
                                        <a href="{% url 'delete_reservation' reservation_type=reservation_type reservation_id=reservation.id %}" class="btn btn-danger">
                                            <i class="fas fa-trash-alt"></i> {% trans "Delete" %}
                                        </a>
                                        -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% empty %}
                        {% if query == '-1' %}
                        <p>{% trans "No cancelled reservations found." %}</p>
                        {% else %}
                        <p>{% trans "No cancelled reservations found matching the search" %} "{{ query }}".</p>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/reception/delete_check_in.html
{% extends './reservations.html' %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Cancel Check-in" %}{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mt-5">{% trans "Cancel check-in" %}</h1>
        <form method="post" class="mt-4 form-control">
            {% csrf_token %}
            <p>{% trans "Are you sure that you want to cancel the check-in" %}: "{{ check_in }}"?</p>
            <button type="submit" class="btn btn-danger">{% trans "Confirm" %}</button>
            <a href="{% url 'reservation_detail' reservation_type=reservation_type reservation_id=reservation_id %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
    </div>
{% endblock %}

templates/reception/delete_reservation.html
{% extends './reservations.html' %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Cancel reservation" %}{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mt-5">{% trans "Cancel reservation" %}</h1>
        <form method="post" class="mt-4 form-control">
            {% csrf_token %}
            <p>{% trans "Are you sure that you want to cancel the reservation" %}: "{{ reservation }}"?</p>
            <button type="submit" class="btn btn-danger">{% trans "Confirm" %}</button>
            <a href="{% url 'reservation_detail' reservation_type=reservation_type reservation_id=reservation_id %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
    </div>
{% endblock %}

templates/reception/edit_check_in.html
{% extends './add_check_in_form.html' %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Edit Check-in" %}{% endblock %}

templates/reception/edit_reservation.html
{% extends './reservations.html' %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Edit reservation" %}{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mt-5">
            {% if reservation_type == 'hotel' %}
                {% trans "Edit room reservation" %}
            {% else %}
                {% trans "Edit restaurant reservation" %}
            {% endif %}
        </h1>
        <form method="post" class="mt-4 form-control">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">{% trans "Save" %}</button>
            <a href="{% url 'reservation_detail' reservation_type=reservation_type reservation_id=reservation_id %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
    </div>
{% endblock %}

templates/reception/reservation_confirmation.html
{% extends 'reception/administration_base.html' %}
{% load i18n %}

{% block title %}Reservation Confirmation{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-5">Reservation Confirmation</h1>
    {% if reservation_type == 'hotel' %}
        <p>Thank you for your reservation. Room ID: {{ room_id }}</p>
        <a class="btn btn-primary mt-3" aria-current="page" href="{% url 'reservations_list' reservation_type='hotel' %}">
            {% trans "Your Reservations" %}
        </a>
    {% else %}
        <p>Thank you for your reservation. Table ID: {{ table_id }}</p>
        <a class="btn btn-primary mt-3" aria-current="page" href="{% url 'reservations_list' reservation_type='restaurant' %}">
            {% trans "Your Reservations" %}
        </a>
    {% endif %}
</div>
{% endblock %}

templates/reception/reservation_detail.html
{% extends './reservations.html' %}
{% load i18n %}
{% load static %}


{% block title %}{% trans "Reservation info" %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1>
        {% if reservation_type == 'hotel' %}
            {% trans "Room reservation" %}
        {% else %}
            {% trans "Restaurant reservation" %}
        {% endif %}
    </h1>
    <hr>
    <div class="card mt-4 shadow">
        <div class="card-header bg-light border-bottom">
            <h5 class="mb-0">Reservation information: {{ reservation }}</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Reservation ID / number:</strong> {{ reservation.id }}</p>
                    {% if reservation_type == 'hotel' %}
                        <p><strong>{% trans "DNI" %}:</strong> {{ reservation.dni }}</p>
                        <p><strong>{% trans "Name" %}:</strong> {{ reservation.first_name }}</p>
                        <p><strong>{% trans "Last name" %}:</strong> {{ reservation.last_name }}</p>
                        <p><strong>{% trans "Email" %}:</strong> {{ reservation.email }}</p>
                        <p><strong>{% trans "Phone" %}:</strong> {{ reservation.phone }}</p>
                        <p><strong>{% trans "Birth" %}:</strong> {{ reservation.date_of_birth }}</p>
                    {% else %}
                        <p><strong>{% trans "Name" %}:</strong> {{ reservation.name }}</p>
                        <p><strong>{% trans "Table ID / number" %}:</strong> {{ reservation.table_id }}</p>
                        <p><strong>{% trans "Time" %}:</strong> {{ reservation.time }}</p>
                    {% endif %}
                </div>
                <div class="col-md-6">
                    {% if reservation_type == 'hotel' %}
                        <p><strong>{% trans "Room type" %}:</strong> {{ reservation.room_type }}</p>
                        <p><strong>{% trans "Room number" %}:</strong> {{ reservation.room_number }}</p>
                        <p><strong>{% trans "Check-In date" %}:</strong> {{ reservation.check_in_date }}</p>
                        <p><strong>{% trans "Check-Out date" %}:</strong> {{ reservation.check_out_date }}</p>
                        <p><strong>{% trans "Number of guests" %}:</strong> {{ reservation.number_of_guests }}</p>
                        <p><strong>{% trans "Price" %}:</strong> {{ reservation.price }}€</p>
                    {% else %}
                        <p><strong>{% trans "Room number" %}:</strong> {{ reservation.room_number }}</p>
                        <p><strong>{% trans "Number of diners" %}:</strong> {{ reservation.number_of_people }}</p>
                    {% endif %}
                </div>
            </div>
            <div class="mt-3">
                {% if reservation_editable %}
                    <a class="btn btn-warning me-2" href="{% url 'edit_reservation' reservation_type=reservation_type reservation_id=reservation_id %}">
                        <i class="fas fa-edit"></i> {% trans "Edit" %}
                    </a>
                    <a class="btn btn-danger me-2" href="{% url 'delete_reservation' reservation_type=reservation_type reservation_id=reservation_id %}">
                        <i class="fas fa-trash-alt"></i> {% trans "Delete" %}
                    </a>
                {% endif %}
                {% if check_in == True %}
                    <a class="btn btn-success" href="{% url 'add_check_in' reservation_type=reservation_type reservation_id=reservation_id %}">
                        <i class="fas fa-sign-in-alt"></i>{% trans "Process Check-In" %}
                    </a>
                {% endif %}
                {% if check_out == True %}
                    <a class="btn btn-success" href="{% url 'add_check_out' reservation_type=reservation_type reservation_id=reservation_id %}">
                        <i class="fas fa-sign-out-alt"></i>{% trans "Process Check-Out" %}
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% if check_in != True and check_in != False %}
        <hr>
        <div class="card mt-4 shadow">
            <div class="card-header bg-light border-bottom">
                <h5 class="mb-0">{% trans "Check-In information:" %} {{ check_in }}</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <p><strong>{% trans "Check-In data" %}:</strong> {{ check_in.guests_data }}</p>
                    </div>
                    <div class="col-6">
                        <p><strong>{% trans "Keys delivered" %}:</strong> {% if check_in.keys == True %}{% trans "Yes" %}{% else %}No{% endif %}</p>
                        <p><strong>{% trans "Created / edited by" %}:</strong> {{ check_in.created_by }}</p>
                    </div>
                </div>
                {% if check_in_editable %}
                    <div class="mt-3">
                        <a class="btn btn-warning me-2" href="{% url 'edit_check_in' reservation_type=reservation_type reservation_id=reservation_id %}">
                            <i class="fas fa-edit"></i> {% trans "Edit" %}
                        </a>
                        <!--
                        <a class="btn btn-danger" href="{% url 'delete_check_in' reservation_type=reservation_type reservation_id=reservation_id %}">
                            <i class="fas fa-trash-alt"></i> {% trans "Delete" %}
                        </a>
                        -->
                    </div>
                {% endif %}
            </div>
        </div>
    {% endif %}
    {% if check_out != True and check_out != False %}
        <hr>
        <div class="card mt-4 shadow">
            <div class="card-header bg-light border-bottom">
                <h5 class="mb-0">{% trans "Check-Out information:" %} {{ check_out }}</h5>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="col-6">
                        <p><strong>{% trans "Price" %}:</strong> {{ check_out.price }}€</p>
                    </div>
                    <div class="col-6">
                        <p><strong>{% trans "Keys collected" %}:</strong> {% if check_out.keys == True %}{% trans "Yes" %}{% else %}No{% endif %}</p>
                        <p><strong>{% trans "Created by" %}:</strong> {{ check_out.created_by }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
</div>
{% endblock %}